In [1]:
import pandas as pd
import numpy as np

In [25]:
data = { 'id' : np.arange(1,101),
         'order_id': np.random.randint(1,300,100),
         'amount': np.random.uniform(100,1100,100)
       }

In [26]:
df = pd.DataFrame(data)

In [27]:
df.groupby('id')['order_id'].count()
sum_a = df.groupby('id',as_index=False)['amount'].sum()
result = sum_a[sum_a['amount']>1000]
result

     id       amount
4     5  1023.545253
16   17  1029.597137
17   18  1069.248261
22   23  1041.580837
53   54  1091.993627
77   78  1012.059872
87   88  1036.459423
91   92  1015.990321
99  100  1055.341322

In [57]:
countries = [
    "United States", "China", "India"
]
countrie = np.random.choice(countries,size=100)
id = np.arange(1,101)
t1 = {
    'id' : id,
    'country': order_id,  
       }
t2 = {
         'id': id,
         'amount': np.random.uniform(100,1100,100)
       }
t1 = pd.DataFrame(t1)
t2 = pd.DataFrame(t2)

In [58]:
merged = pd.merge(t1,t2, on='id')
filtered = merged.groupby('country').count()
merged

     id  country       amount
0     1      297   873.021982
1     2      159   331.716293
2     3      292   429.738676
3     4       21   352.850306
4     5       81   777.692025
..  ...      ...          ...
95   96      254   235.523505
96   97       30   782.725542
97   98      165   545.086073
98   99      156   992.256808
99  100      242  1056.466955

[100 rows x 3 columns]

In [59]:
mean_country = merged.groupby('country')['amount'].mean()