In [15]:
import pandas as pd
import numpy as np

In [ ]:
 date = (f'{y}-{m}-{d}')

In [16]:
data = { 'id' : np.arange(1,101),
         'order_id': np.random.randint(1,300,100),
         'amount': np.random.uniform(100,1100,100)
       }

In [17]:
df = pd.DataFrame(data)

In [26]:
result = (df.groupby('id').agg(order_count=('order_id','count'),total_am=('amount','sum')).reset_index())
result

     id  order_count     total_am
0     1            1   587.995557
1     2            1  1006.099149
2     3            1   245.326782
3     4            1   264.004878
4     5            1   836.351739
..  ...          ...          ...
95   96            1   490.073406
96   97            1   431.550361
97   98            1  1033.171647
98   99            1   635.504737
99  100            1  1038.602922

[100 rows x 3 columns]

In [27]:
countries = [
    "United States", "China", "India"
]
countrie = np.random.choice(countries,size=100)
order_id = np.arange(101,201)
id = np.arange(1,101)
t1 = {
    'id' : id,
    'country': countrie,  
       }
t2 = {
         'id': id,
         'amount': np.random.uniform(100,1100,100)
       }
t1 = pd.DataFrame(t1)
t2 = pd.DataFrame(t2)

In [33]:
merged = pd.merge(t1,t2, on='id')
filtered = merged.groupby('country').agg(
    avg_amount=('amount','mean'),
    orders_count=('amount','count')
)
filtered = filtered[filtered['orders_count']>10]
filtered

               avg_amount  orders_count
country
China          547.764469            33
India          608.363265            38
United States  495.389541            29

In [76]:
date = (f'{np.random.randint(2004,2015)}-{np.random.randint(1,12)}-{np.random.randint(1,31)}')
date_series = (f'{np.random.randint(2004,2015)}-{np.random.randint(1,12)}-{np.random.randint(1,31)}' for i in range(100))
date_series = pd.Series(date_series)
date_series = pd.to_datetime(date_series, errors='coerce')
df = { 'id' : np.arange(1,101),
         'date': date_series,
       }

df = pd.DataFrame(df)

df['year_month'] = df['date'].dt.to_period('M')

grouped = df.groupby('year_month')['id'].nunique()

grouped

year_month
2004-01    2
2004-02    1
2004-03    2
2004-06    1
2004-07    2
          ..
2014-06    1
2014-07    1
2014-08    3
2014-09    1
2014-10    1
Freq: M, Name: id, Length: 68, dtype: int64